server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - AuthenticationFilter
      routes:
        - id: appointment-service
          uri: http://localhost:8082
          predicates:
            - Path=/appointments/**
          filters:
            - AuthenticationFilter

jwt:
  secret: my-secret-key
  expiration: 3600000 # 1 hour